sudo: false

language: node_js

node_js:
  - node

services:
  - mysql

addons:
  - mariadb

install:
  - npm ci

before_script:
  - mysql -u root
  - mysql CREATE DATABASE IF NOT EXISTS ODFBC
  - mysql root < ./db_script.sql

script:
  - npm test